### ISSUE TITLE
How to simulate data with binary phenotype?

### ISSUE THREAD

**Issue by KasperFischer** [baumbachlab/epigen#1]

**Comment by dbblumenthal** [comment]
The phenotypes are specified in the model files, passed to simulate_data.py via the --model argument. In the model files, you can specify the phenotype via the attribute "phenotype" (see models/ext_model.ini and models/param_model.xml for examples). Acceptable values are "quantitative" or natural numbers c >= 2 for categorical phenotypes with c categories. Binary phenotypes are simply a special case of categorical phenotypes, so you have to set the value of the attribute "phenotype" to 2.
