### ISSUE TITLE
Remove single loci marginal effect

### ISSUE THREAD

**Issue by msantorsola** [baumbachlab/epigen#4]
Dear all,

Our goal is to simulate **pure epistatic interactions**, where no single SNP exhibits a marginal effect. 

To achieve this, we have attempted to use the following parameter setting:

- 2 SNPs
- 	the marginal interaction alpha = 1
- 	the baseline alpha = 0.1
- 	the interaction alpha equal to 15 _or_ 30
- 	--disease-maf-range set to [0.08 - 0.25] _or_ [0.3 - 0.45]

Here the model:

`<!DOCTYPE ParametrizedModel SYSTEM "ParametrizedModel.dtd">
<ParametrizedModel size="2" phenotype="2">
    <BaselineModel alpha="0.1"/>
     <InteractionModel alpha="15" type="multiplicative">
        <pos>0</pos>
        <pos>1</pos>
    </InteractionModel>   
    <MarginalModel alpha="1" type="additive">
        <pos>1</pos>
    </MarginalModel>
</ParametrizedModel>`

	
and the command line used:

`python3 simulate_data.py --seed 1 --sim-ids 27 --corpus-id ${CHR} --pop ${POP} --snps 10000 --inds 5000  --disease-maf-range 0.08 0.25 --model models/multiplicative_additive_baseline0.1_marginal1_interaction15.xml`

Anyway, at each attempt we still obtain a significant marginal effect for a single locus:

Simulation ID | --disease-maf-range | BaselineModel   alpha | MarginalModel   alpha | InteractionModel   alpha | glm   SNP1 | glm   SNP2 | Epigen chi-square test p_value
-- | -- | -- | -- | -- | -- | -- | --
1 | 0.08   - 0.25 | 0.1 | 1 | 15 | 0 | 0 | 0
2 | 0.08   - 0.25 | 0.1 | 1 | 30 | 0 | 0 | 0
3 | 0.3   - 0.45 | 0.1 | 1 | 15 | 0 | 0.00003117728122 | 0
4 | 0.3   - 0.45 | 0.1 | 1 | 30 | 0 | 0.000003640559822 | 0

Moreover, does Epigen simulate epistatic interactions besides pairwise ones (i.e. among SNPs >= 3)?

**Comment by dbblumenthal** [comment]
Dear msantorsola,

thanks for raising this issue. You ran EpiGen with a parametrized epistasis model that uses multiplicative interaction. Multiplicative interaction does lead to marginal effects (see Fig 2a in the paper), so the results you obtained are as expected. The same holds for any other of the parametrized interaction models shipped with EpiGEN. 

If you want to simulated pure epistasis w/o marginal effects, you have two options: (1) Define a custom parametrized interaction model (see Section 1.4 in user guide). (2) Use an extensionally defined epistasis model where you explicitly define the probability distributions for all possible genotypes at the epistatis SNPs such there are no marginal effects (see page 5 in user guide). 

EpiGEN also allows to simulate higher-order epistasis. You just have to set the "size" attribute of the epistasis models to the desired order. For parametrized models, an example with size=3 is given in epigen/models/param_model.xml. For extensional models, you would have to explicitly write down the probability distributions each of the 3^{size} possible genotypes at the epistasis SNPs.

Best,

David

**Comment by msantorsola** [comment]
Hi there, 

thanks for your quick reply.

Maybe due to our limitations, we submitted an issue because we couldn't build the desired model simply by reading the user guide. 

It would be very appreciated if you could reply with an example of a model like the one we'd like to build. 

Best,
Mariangela
